#!/bin/bash -l

#SBATCH --job-name=epihiperdb
#SBATCH -t 72:00:00
#SBATCH -p bii 
#SBATCH -A bii_nssac
#SBATCH --exclusive

DATAFOLDER=/home/shoops/git/EpiHiper/sciduct/data
HOSTNAME=$(hostname)
IMG=/home/shoops/git/EpiHiper/sciduct/postgres-11.4.simg
DB=epihiper_db
DBUSER=epihiper
DBPASS=epihiper
SLURM_JOB_ID=PG

if [ _$1 == _"stop" ]; then
  # shutdown the db cleanly
  echo "Stop DB"
  singularity run --app stop instance://$SLURM_JOB_ID

  # stop the singularity instance
  echo "Stop Singularity Instance"
  singularity instance stop $SLURM_JOB_ID

  exit
fi

# Echo the starting date (if this works)
echo "Starting instance ..."
date

if [ _$1 == _"create" ]; then
  # create the database data directory locally
  echo "Creating data dir: $DATAFOLDER"
  mkdir -p $DATAFOLDER
    
  # start instance
  echo "Start Instance"
  singularity instance start --bind $DATAFOLDER:/data $IMG $SLURM_JOB_ID

  echo "Start postgresql"
  singularity run --app start instance://$SLURM_JOB_ID 

  # run createdb
  echo "Create DB $DB"
  singularity run --app createdb instance://$SLURM_JOB_ID $DB

  # run createuser args are <user> <pass> <database>
  singularity run --app createuser instance://$SLURM_JOB_ID $DBUSER $DBPASS $DB
else
  # start instance
  echo "Start Instance"
  singularity instance start --bind $DATAFOLDER:/data $IMG $SLURM_JOB_ID

  echo "Start postgresql"
  singularity run --app start instance://$SLURM_JOB_ID 
fi

# get connection host and port
CONNECTION=$(singularity run --app connection instance://$SLURM_JOB_ID)

#DO Stuff with the db 
echo "DB running on $CONNECTION"
# sleep 20000

