# Base Image
FROM archlinux:base-devel 

# Update system
RUN pacman --noconfirm -Syu

# required
RUN pacman --noconfirm -S git cmake postgresql-libs

# OpenMPI (optional)
RUN pacman --noconfirm -S openmpi

# Build EpiHiper
CMD cd /home && \
    git clone https://github.com/NSSAC/EpiHiper.git && \
    mkdir build && \
    cd build && \
    cmake -G "Unix Makefiles" -DENABLE_MPI=ON -DENABLE_OMP=ON -DENABLE_LOCATION_ID=ON ../EpiHiper && \
    make -j 4 && \
    make test
